### ISSUE TITLE
KUBECTL_PLUGINS_GLOBAL_FLAG_NAMESPACE won't work anymore

### ISSUE THREAD

**Issue by ahmetb** [jpdasma/exec-all#1]
As of kubectl 1.12, kubectl stopped passing KUBECTL_ env vars to plugins. FYI.

**Comment by ahmetb** [comment]
This'll break the -c functionality, and -p functionality. Basically all flags are broken.

**Comment by jpdasma** [comment]
Thanks for the heads up. I'll fix that.

**Comment by jpdasma** [comment]
Fixed with https://github.com/jpdasma/kubectl-exec-all/commit/581250875c1b4528bb8371f9496ad3ff7bab5765
